### ISSUE TITLE
images

### ISSUE THREAD

**Issue by kennyfs** [chengstone/cchess-zero#3]
images的图片的副档名应该是小写的gif吧？

**Comment by BH1SCW** [comment]
_tkinter.TclError: couldn't open "images/WHITE.gif": no such file or directory
同样的问题， 可能是在window上开发的？没区分大小写

**Comment by chengstone** [comment]
我刚注意到，确实文件扩展名跟代码对不上，但是我的Mac认为两者是同一个文件，扩展名的修改系统不认为该文件有改动，因此GitHub软件不让上传。。。

**Comment by chengstone** [comment]
棋盘UI这部分使用的开源项目，直接拿过来用了，没有review过，不过我在Windows和Mac上面都运行过，没有出过问题，所以也没有注意到文件扩展名大小写的问题。感谢两位的提醒。
使用的棋盘开源项目如下：
https://github.com/lifei96/IntelliChess
https://github.com/Linzertorte/ChineseChess
