### ISSUE TITLE
little problem

### ISSUE THREAD

**Issue by songwaimai** [chengstone/cchess-zero#6]
您好，感谢您的分享~现在想问您关于ma.py的程序中
 if (x if abs(dx) ==1 else x+dx/2, y if abs(dy) ==1 else y+ (dy/2)) in board.pieces:
            #print 'blocked'
            return False
这块是什么意思呢~

**Comment by songwaimai** [comment]
还有就是您的piece是指棋子吗

**Comment by kennyfs** [comment]
> 还有就是您的piece是指棋子吗

對
